(* Patched for use with FeynCalc *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"InertDoublet",
  Authors -> {"Andreas Goudelis, Bjoern Herrmann, Oscal Stal"},
  Version -> "1.0",
  Date -> "04. 10. 2013",
  Institutions -> {"LAPTh-Annecy, Oscar Klein Center-Stockholm"},
  Emails -> {"andreas.goudelis@lapth.cnrs.fr"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{HIG, 0}, {QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

(*     Declared particles    *)

M$ClassesDescription = {
F[1] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation]},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mnu },

F[2] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation]},
    QuantumNumbers -> {-Q},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation], Index[Colour]},
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Generation], Index[Colour]},
    QuantumNumbers -> {-1/3*Q},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

V[1] == {
    SelfConjugate -> True,
    Indices -> {},
    PropagatorLabel -> "\\gamma",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0 },

V[2] == {
    SelfConjugate -> True,
    Indices -> {},
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"] },

V[3] == {
    SelfConjugate -> False,
    Indices -> {},
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"] },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    Indices -> {},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> uA,
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

U[2] == {
    SelfConjugate -> False,
    Indices -> {},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> uZ,
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MZ"] },

U[3] == {
    SelfConjugate -> False,
    Indices -> {},
    QuantumNumbers -> {Q, GhostNumber},
    PropagatorLabel -> uWp,
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"] },

U[4] == {
    SelfConjugate -> False,
    Indices -> {},
    QuantumNumbers -> {-Q, GhostNumber},
    PropagatorLabel -> uWm,
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> FCGV["MW"] },

U[5] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> uG,
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

S[1] == {
    SelfConjugate -> True,
    Indices -> {},
    PropagatorLabel -> "h",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mh },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "G0",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> FCGV["MZ"],
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    PropagatorLabel -> "Gch",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    QuantumNumbers -> {Q},
    Mass -> FCGV["MW"],
    Indices -> {} },

S[4] == {
    SelfConjugate -> True,
    Indices -> {},
    PropagatorLabel -> "H0",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH0 },

S[5] == {
    SelfConjugate -> True,
    Indices -> {},
    PropagatorLabel -> "A0",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MA0 },

S[6] == {
    SelfConjugate -> False,
    Indices -> {},
    QuantumNumbers -> {Q},
    PropagatorLabel -> "Hch",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> Forward,
    Mass -> MHch }
}


(*        Definitions       *)


Mnu[ 1 ] := Mnue;
Mnu[ 2 ] := Mnum;
Mnu[ 3 ] := Mnut;
Ml[ 1 ] := FCGV["ME"];
Ml[ 2 ] := FCGV["MM"];
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := FCGV["MU"];
Mu[ 1 ] := FCGV["MU"];
Mu[ 2, _ ] := FCGV["MC"];
Mu[ 2 ] := FCGV["MC"];
Mu[ 3, _ ] := FCGV["MT"];
Mu[ 3 ] := FCGV["MT"];
Md[ 1, _ ] := FCGV["MD"];
Md[ 1 ] := FCGV["MD"];
Md[ 2, _ ] := FCGV["MS"];
Md[ 2 ] := FCGV["MS"];
Md[ 3, _ ] := FCGV["MB"];
Md[ 3 ] := FCGV["MB"];
FCGV["MZ"][ ___ ] := FCGV["MZ"];
FCGV["MW"][ ___ ] := FCGV["MW"];
mh[ ___ ] := mh;
MH0[ ___ ] := MH0;
MA0[ ___ ] := MA0;
MHch[ ___ ] := MHch;


TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "m";
TheLabel[ F[2, {3}] ] := "tau";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";
TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[5, {__}] ] := TheLabel[U[5]];


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{(-6*I)*lam, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(-2*I)*lam, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{(-4*I)*lam, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(-2*I)*lam, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{(-6*I)*lam, 0}},

C[ S[5] , S[5] , S[5] , S[5] ] == {{(-6*I)*lam2, 0}},

C[ S[5] , S[5] , S[4] , S[4] ] == {{(-2*I)*lam2, 0}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{(-6*I)*lam2, 0}},

C[ S[5] , S[5] , S[6] , -S[6] ] == {{(-2*I)*lam2, 0}},

C[ S[4] , S[4] , S[6] , -S[6] ] == {{(-2*I)*lam2, 0}},

C[ S[6] , S[6] , -S[6] , -S[6] ] == {{(-4*I)*lam2, 0}},

C[ S[5] , S[5] , S[2] , S[2] ] == {{(-I)*(lam3 + lam4 + lam5), 0}},

C[ S[5] , S[5] , S[3] , -S[3] ] == {{(-I)*lam3, 0}},

C[ S[5] , S[5] , S[1] , S[1] ] == {{(-I)*(lam3 + lam4 - lam5), 0}},

C[ S[2] , S[2] , S[4] , S[4] ] == {{(-I)*(lam3 + lam4 - lam5), 0}},

C[ S[3] , -S[3] , S[4] , S[4] ] == {{(-I)*lam3, 0}},

C[ S[1] , S[1] , S[4] , S[4] ] == {{(-I)*(lam3 + lam4 + lam5), 0}},

C[ S[2] , S[2] , S[6] , -S[6] ] == {{(-I)*lam3, 0}},

C[ S[3] , -S[3] , S[6] , -S[6] ] == {{(-I)*(lam3 + lam4), 0}},

C[ S[1] , S[1] , S[6] , -S[6] ] == {{(-I)*lam3, 0}},

C[ S[5] , S[2] , -S[3] , S[6] ] == {{(-1/2*I)*(lam4 + lam5), 0}},

C[ S[5] , -S[3] , S[1] , S[6] ] == {{(-lam4 + lam5)/2, 0}},

C[ S[2] , -S[3] , S[4] , S[6] ] == {{(lam4 - lam5)/2, 0}},

C[ -S[3] , S[1] , S[4] , S[6] ] == {{(-1/2*I)*(lam4 + lam5), 0}},

C[ S[5] , S[2] , S[3] , -S[6] ] == {{(-1/2*I)*(lam4 + lam5), 0}},

C[ S[5] , S[3] , S[1] , -S[6] ] == {{(lam4 - lam5)/2, 0}},

C[ S[2] , S[3] , S[4] , -S[6] ] == {{(-lam4 + lam5)/2, 0}},

C[ S[3] , S[1] , S[4] , -S[6] ] == {{(-1/2*I)*(lam4 + lam5), 0}},

C[ S[5] , S[2] , S[1] , S[4] ] == {{(-I)*lam5, 0}},

C[ -S[3] , -S[3] , S[6] , S[6] ] == {{(-2*I)*lam5, 0}},

C[ S[3] , S[3] , -S[6] , -S[6] ] == {{(-2*I)*lam5, 0}},

C[ S[2] , S[2] , S[1] ] == {{(-2*I)*lam*v, 0}},

C[ S[3] , -S[3] , S[1] ] == {{(-2*I)*lam*v, 0}},

C[ S[1] , S[1] , S[1] ] == {{(-6*I)*lam*v, 0}},

C[ S[5] , S[5] , S[1] ] == {{(-I)*(lam3 + lam4 - lam5)*v, 0}},

C[ S[1] , S[4] , S[4] ] == {{(-I)*(lam3 + lam4 + lam5)*v, 0}},

C[ S[1] , S[6] , -S[6] ] == {{(-I)*lam3*v, 0}},

C[ S[5] , -S[3] , S[6] ] == {{-1/2*((lam4 - lam5)*v), 0}},

C[ -S[3] , S[4] , S[6] ] == {{(-1/2*I)*(lam4 + lam5)*v, 0}},

C[ S[5] , S[3] , -S[6] ] == {{((lam4 - lam5)*v)/2, 0}},

C[ S[3] , S[4] , -S[6] ] == {{(-1/2*I)*(lam4 + lam5)*v, 0}},

C[ S[5] , S[2] , S[4] ] == {{(-I)*lam5*v, 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*FCGV["EL"]^2, 0}},

C[ S[6] , -S[6] , V[1] , V[1] ] == {{(2*I)*FCGV["EL"]^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc46, 0}, {I*gc46, 0}},

C[ S[6] , -S[6] , V[1] ] == {{(-I)*gc47, 0}, {I*gc47, 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] ] == {{(-I)*gc48*IndexDelta[e1x2, e2x2], 0}, {I*gc48*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -U[1] , U[4] , V[3] ] == {{I*gc49, 0}, {I*gc49, 0}, {0, 0}},

C[ -U[1] , U[3] , -V[3] ] == {{I*gc50, 0}, {I*gc50, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[1] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ -U[4] , U[1] , -V[3] ] == {{I*gc52, 0}, {I*gc52, 0}, {0, 0}},

C[ S[2] , -U[4] , U[4] ] == {{-1/4*(FCGV["EL"]^2*v)/FCGV["SW"]^2, 0}},

C[ S[1] , -U[4] , U[4] ] == {{((-1/4*I)*FCGV["EL"]^2*v)/FCGV["SW"]^2, 0}},

C[ -U[4] , U[4] , V[1] ] == {{I*gc55, 0}, {I*gc55, 0}, {0, 0}},

C[ -U[4] , U[4] , V[2] ] == {{I*gc56, 0}, {I*gc56, 0}, {0, 0}},

C[ -S[3] , -U[4] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"])*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[4] , U[2] , -V[3] ] == {{I*gc58, 0}, {I*gc58, 0}, {0, 0}},

C[ S[3] , -U[3] , U[1] ] == {{((-1/2*I)*FCGV["EL"]^2*v)/FCGV["SW"], 0}},

C[ -U[3] , U[1] , V[3] ] == {{I*gc60, 0}, {I*gc60, 0}, {0, 0}},

C[ S[2] , -U[3] , U[3] ] == {{(FCGV["EL"]^2*v)/(4*FCGV["SW"]^2), 0}},

C[ S[1] , -U[3] , U[3] ] == {{((-1/4*I)*FCGV["EL"]^2*v)/FCGV["SW"]^2, 0}},

C[ -U[3] , U[3] , V[1] ] == {{I*gc63, 0}, {I*gc63, 0}, {0, 0}},

C[ -U[3] , U[3] , V[2] ] == {{I*gc64, 0}, {I*gc64, 0}, {0, 0}},

C[ S[3] , -U[3] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"])*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[3] , U[2] , V[3] ] == {{I*gc66, 0}, {I*gc66, 0}, {0, 0}},

C[ S[3] , -U[2] , U[4] ] == {{((I/4)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[2] , U[4] , V[3] ] == {{I*gc68, 0}, {I*gc68, 0}, {0, 0}},

C[ -S[3] , -U[2] , U[3] ] == {{((I/4)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)*v)/(FCGV["CW"]*FCGV["SW"]^2), 0}},

C[ -U[2] , U[3] , -V[3] ] == {{I*gc70, 0}, {I*gc70, 0}, {0, 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-1/4*I)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*v)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ -U[5, {e1x1}] , U[5, {e2x1}] , V[4, {e3x2}] ] == {{gc72*FASUNF[e3x2, e1x1, e2x1], 0}, {gc72*FASUNF[e3x2, e1x1, e2x1], 0}, {0, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc73*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc73*FASUNF[e1x2, e2x2, e3x2], 0}, {gc73*FASUNF[e1x2, e2x2, e3x2], 0}, {-(gc73*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(gc73*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc73*FASUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc74*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc74*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc74*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc75*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc75*FASUNF[e1x2, e2x2, e3x2], 0}, {gc75*FASUNF[e1x2, e2x2, e3x2], 0}, {-(gc75*FASUNF[e1x2, e2x2, e3x2]), 0}, {-(gc75*FASUNF[e1x2, e2x2, e3x2]), 0}, {gc75*FASUNF[e1x2, e2x2, e3x2], 0}},

C[ S[1] , V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc76*(FASUNF[e1x2, e2x2, e3x2, e4x2] + FASUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc76*(FASUNF[e1x2, e2x2, e3x2, e4x2] - FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc76*(FASUNF[e1x2, e3x2, e2x2, e4x2] + FASUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[2] ] == {{gc77L[e1x2]*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc77R[e1x2]*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc78[e1x2]*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc78[e1x2]*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -S[3] ] == {{I*gc79L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc79R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[3] ] == {{I*gc80L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc80R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[2] ] == {{gc81L[e1x2]*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc81R[e1x2]*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc82[e1x2]*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc82[e1x2]*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[2] ] == {{0, 0}, {gc83R[e1x2]*IndexDelta[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{0, 0}, {I*gc84R[e1x2]*IndexDelta[e1x2, e2x2], 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[3] ] == {{0, 0}, {I*gc85R[e1x2]*IndexDelta[e1x2, e2x2], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc86*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], 0}, {I*gc86*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc87*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], 0}, {I*gc87*IndexDelta[e1x2, e2x2]*FASUNT[e3x2, e1x3, e2x3], 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{-1/2*FCGV["EL"]^2/FCGV["SW"], 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"], 0}},

C[ S[5] , -S[6] , V[1] , V[3] ] == {{-1/2*FCGV["EL"]^2/FCGV["SW"], 0}},

C[ S[4] , -S[6] , V[1] , V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"], 0}},

C[ -S[3] , V[1] , V[3] ] == {{0, 0}, {0, 0}, {I*gc92, 0}},

C[ S[5] , -S[6] , V[3] ] == {{-gc93, 0}, {gc93, 0}},

C[ S[2] , -S[3] , V[3] ] == {{-gc94, 0}, {gc94, 0}},

C[ -S[3] , S[1] , V[3] ] == {{(-I)*gc95, 0}, {I*gc95, 0}},

C[ S[4] , -S[6] , V[3] ] == {{(-I)*gc96, 0}, {I*gc96, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc97, 0}, {I*gc97, 0}, {I*gc97, 0}, {(-I)*gc97, 0}, {(-I)*gc97, 0}, {I*gc97, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{FCGV["EL"]^2/(2*FCGV["SW"]), 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"], 0}},

C[ S[5] , S[6] , V[1] , -V[3] ] == {{FCGV["EL"]^2/(2*FCGV["SW"]), 0}},

C[ S[4] , S[6] , V[1] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"], 0}},

C[ S[3] , V[1] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc102, 0}},

C[ S[5] , S[6] , -V[3] ] == {{-gc103, 0}, {gc103, 0}},

C[ S[2] , S[3] , -V[3] ] == {{-gc104, 0}, {gc104, 0}},

C[ S[3] , S[1] , -V[3] ] == {{(-I)*gc105, 0}, {I*gc105, 0}},

C[ S[4] , S[6] , -V[3] ] == {{(-I)*gc106, 0}, {I*gc106, 0}},

C[ S[5] , S[5] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[4] , S[4] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[6] , -S[6] , V[3] , -V[3] ] == {{((I/2)*FCGV["EL"]^2)/FCGV["SW"]^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{0, 0}, {0, 0}, {I*gc113, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc114, 0}, {(-I)*gc114, 0}, {(2*I)*gc114, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc115, 0}, {I*gc115, 0}, {I*gc115, 0}, {(-I)*gc115, 0}, {(-I)*gc115, 0}, {I*gc115, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc116, 0}, {(-I)*gc116, 0}, {(2*I)*gc116, 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"]))/(FCGV["CW"]*FCGV["SW"]), 0}},

C[ S[6] , -S[6] , V[1] , V[2] ] == {{(I*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])*(FCGV["CW"] + FCGV["SW"]))/(FCGV["CW"]*FCGV["SW"]), 0}},

C[ S[5] , S[4] , V[2] ] == {{-gc119, 0}, {gc119, 0}},

C[ S[2] , S[1] , V[2] ] == {{-gc120, 0}, {gc120, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc121, 0}, {I*gc121, 0}},

C[ S[6] , -S[6] , V[2] ] == {{(-I)*gc122, 0}, {I*gc122, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{FCGV["EL"]^2/(2*FCGV["CW"]), 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2)/FCGV["CW"], 0}},

C[ S[5] , -S[6] , V[3] , V[2] ] == {{FCGV["EL"]^2/(2*FCGV["CW"]), 0}},

C[ S[4] , -S[6] , V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2)/FCGV["CW"], 0}},

C[ -S[3] , V[3] , V[2] ] == {{0, 0}, {0, 0}, {I*gc127, 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{-1/2*FCGV["EL"]^2/FCGV["CW"], 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2)/FCGV["CW"], 0}},

C[ S[5] , S[6] , -V[3] , V[2] ] == {{-1/2*FCGV["EL"]^2/FCGV["CW"], 0}},

C[ S[4] , S[6] , -V[3] , V[2] ] == {{((-1/2*I)*FCGV["EL"]^2)/FCGV["CW"], 0}},

C[ S[3] , -V[3] , V[2] ] == {{0, 0}, {0, 0}, {I*gc132, 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc133, 0}, {I*gc133, 0}, {I*gc133, 0}},

C[ S[5] , S[5] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])^2*(FCGV["CW"] + FCGV["SW"])^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[4] , S[4] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[6] , -S[6] , V[2] , V[2] ] == {{((I/2)*FCGV["EL"]^2*(FCGV["CW"] - FCGV["SW"])^2*(FCGV["CW"] + FCGV["SW"])^2)/(FCGV["CW"]^2*FCGV["SW"]^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{0, 0}, {0, 0}, {I*gc140, 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc141, 0}, {(-I)*gc141, 0}, {(2*I)*gc141, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc142*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc142*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc143*IndexDelta[e1x2, e2x2], 0}, {I*gc143*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc144*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc144*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc145*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc146[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc147*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc148[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc149L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc149R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc150L*IndexDelta[e1x2, e2x2], 0}, {I*gc150R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc151L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc151R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc152*IndexDelta[e1x2, e2x2], 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc46 -> -FCGV["EL"],
     gc47 -> -FCGV["EL"],
     gc48 -> GH,
     gc49 -> FCGV["EL"],
     gc50 -> -FCGV["EL"],
     gc52 -> FCGV["EL"],
     gc55 -> -FCGV["EL"],
     gc56 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc58 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc60 -> -FCGV["EL"],
     gc63 -> FCGV["EL"],
     gc64 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc66 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc68 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc70 -> -((FCGV["CW"]*FCGV["EL"])/FCGV["SW"]),
     gc72 -> FAGS,
     gc73 -> -FAGS,
     gc74 -> -FAGS^2,
     gc75 -> -(GH*FAGS),
     gc76 -> -(GH*FAGS^2),
     gc77L[e1x2_] -> -(Md[e1x2]/v),
     gc77R[e1x2_] -> Md[e1x2]/v,
     gc78[e1x2_] -> -(Md[e1x2]/v),
     gc79L[e1x2_, e2x2_] -> -((Sqrt[2]*Conjugate[CKM[e2x2, e1x2]]*Md[e2x2])/v),
     gc79R[e1x2_, e2x2_] -> (Sqrt[2]*Conjugate[CKM[e2x2, e1x2]]*Mu[e1x2])/v,
     gc80L[e1x2_, e2x2_] -> (Sqrt[2]*CKM[e1x2, e2x2]*Mu[e2x2])/v,
     gc80R[e1x2_, e2x2_] -> -((Sqrt[2]*CKM[e1x2, e2x2]*Md[e1x2])/v),
     gc81L[e1x2_] -> Mu[e1x2]/v,
     gc81R[e1x2_] -> -(Mu[e1x2]/v),
     gc82[e1x2_] -> -(Mu[e1x2]/v),
     gc83R[e1x2_] -> Ml[e1x2]/v,
     gc84R[e1x2_] -> -(Ml[e1x2]/v),
     gc85R[e1x2_] -> -((Sqrt[2]*Ml[e1x2])/v),
     gc86 -> FAGS,
     gc87 -> FAGS,
     gc92 -> (FCGV["EL"]^2*v)/(2*FCGV["SW"]),
     gc93 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc94 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc95 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc96 -> -1/2*FCGV["EL"]/FCGV["SW"],
     gc97 -> FCGV["EL"],
     gc102 -> (FCGV["EL"]^2*v)/(2*FCGV["SW"]),
     gc103 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc104 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc105 -> -1/2*FCGV["EL"]/FCGV["SW"],
     gc106 -> FCGV["EL"]/(2*FCGV["SW"]),
     gc113 -> (FCGV["EL"]^2*v)/(2*FCGV["SW"]^2),
     gc114 -> -FCGV["EL"]^2,
     gc115 -> (FCGV["CW"]*FCGV["EL"])/FCGV["SW"],
     gc116 -> FCGV["EL"]^2/FCGV["SW"]^2,
     gc119 -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc120 -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc121 -> -1/2*(FCGV["CW"]*FCGV["EL"])/FCGV["SW"] + (FCGV["EL"]*FCGV["SW"])/(2*FCGV["CW"]),
     gc122 -> -1/2*(FCGV["CW"]*FCGV["EL"])/FCGV["SW"] + (FCGV["EL"]*FCGV["SW"])/(2*FCGV["CW"]),
     gc127 -> -1/2*(FCGV["EL"]^2*v)/FCGV["CW"],
     gc132 -> -1/2*(FCGV["EL"]^2*v)/FCGV["CW"],
     gc133 -> (FCGV["CW"]*FCGV["EL"]^2)/FCGV["SW"],
     gc140 -> (FCGV["EL"]^2*(FCGV["CW"]^2 + FCGV["SW"]^2)^2*v)/(2*FCGV["CW"]^2*FCGV["SW"]^2),
     gc141 -> -((FCGV["CW"]^2*FCGV["EL"]^2)/FCGV["SW"]^2),
     gc142 -> -1/3*FCGV["EL"],
     gc143 -> -FCGV["EL"],
     gc144 -> (2*FCGV["EL"])/3,
     gc145 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc146[e1x2_, e2x2_] -> (FCGV["EL"]*CKM[e1x2, e2x2])/(Sqrt[2]*FCGV["SW"]),
     gc147 -> FCGV["EL"]/(Sqrt[2]*FCGV["SW"]),
     gc148[e1x2_, e2x2_] -> (FCGV["EL"]*Conjugate[CKM[e2x2, e1x2]])/(Sqrt[2]*FCGV["SW"]),
     gc149L -> -1/6*(FCGV["EL"]*(3*FCGV["CW"]^2 + FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc149R -> (FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc150L -> -1/2*(FCGV["EL"]*(FCGV["CW"]^2 - FCGV["SW"]^2))/(FCGV["CW"]*FCGV["SW"]),
     gc150R -> (FCGV["EL"]*FCGV["SW"])/FCGV["CW"],
     gc151L -> (FCGV["CW"]*FCGV["EL"])/(2*FCGV["SW"]) - (FCGV["EL"]*FCGV["SW"])/(6*FCGV["CW"]),
     gc151R -> (-2*FCGV["EL"]*FCGV["SW"])/(3*FCGV["CW"]),
     gc152 -> (FCGV["EL"]*(FCGV["CW"]^2 + FCGV["SW"]^2))/(2*FCGV["CW"]*FCGV["SW"])};

